### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by daiki0381** [daiki0381/duet-code#2]
【フロントエンド】Next.js
【バックエンド】Rails APIモード

## ER図

![Image](https://user-images.githubusercontent.com/98577773/198817202-53f9e73d-9a88-40a2-b4f8-4fe795e6811d.png)

## User

カラム名 | データ型  | 説明
-- | -- | -- |
id | integer | 主キー
uid | string | Firebase AuthenticationのGitHub認証のユーザー識別子
github_access_token | string | GitHubのアクセストークン
name | string | ユーザー名
avatar | string | アバター画像

## Review

カラム名 | データ型 | 説明
-- | -- | -- |
id | integer | 主キー
reviewee_id | integer | 外部キー
reviewer_id | integer | 外部キー
title | string | タイトル
repository | string | リポジトリ
pull_request_title | string | プルリクエストのタイトル
pull_request_url | string | プルリクエストのURL
pull_request_description | text | プルリクエストの説明
review_point | text |レビューしてほしい点
feedback | text | フィードバック
thanks | text | お礼
accepted_at | datetime | レビューする側の承諾日時

## ReviewLanguage

カラム名 | データ型 | 説明
-- | -- | -- |
id | integer | 主キー
review_id | integer | 外部キー
language_id | integer | 外部キー

## Language

カラム名 | データ型 | 説明
-- | -- | -- |
id | integer | 主キー
name | string | 言語名

## Notification

カラム名 | データ型 | 説明
-- | -- | -- |
id | integer | 主キー
review_id | integer | 外部キー
sender_id | integer | 外部キー
receiver_id | integer | 外部キー
action | string | 通知の種類
checked | boolean | 通知を確認したか

**Comment by yuuu** [comment]
それぞれコメントしますね。

- Postというテーブル名は抽象的すぎていろいろな投稿物に使えてしまうのでもう少し具体的な名前の方が良いですね。
- レビューを承認したとき、 `done` を `true` とする理解であっていますでしょうか？
    - もしそうであれば、ここは承認した時刻を知りたくなる可能性があるので、Datetimeとしておくと良いかもしれません
- お礼・フィードバックは、1つのレビューに対して1回ずつしかできない、という仕様で合っていますか？
    - レビューが1回で終わらない場合(修正して欲しい箇所がある場合)にどうするのかが気になりました。
- お礼・フィードバックは空入力にできないという仕様で合っていますか？
    - もし空入力を許容すると、レビュー完了・フィードバック完了というステータスを判定する手段がないように見えました。
    - 別途 `status` のようなカラムを設けるか、お礼日時・フィードバック日時のようなカラムを用意しても良いかもしれません
- これはペーパープロトタイプに対する質問ですが、レビューの申し出があったものの、承認したくない(別の人にレビューして欲しい)場合、拒否する手段はあるのでしょうか？
- Languageテーブルの主キーは `language` という理解で良いでしょうか？Railsで作るなら `id` を別途設けておいた方が作りやすいと思われるため確認しています。
- Notificationについてユーザーとのリレーションは不要でしょうか？
    - もし不要である場合、 `checked` は誰が確認したことを示すのか気になりました

**Comment by daiki0381** [comment]
@yuuu レビューありがとうございます🙇‍♂️

> Postというテーブル名は抽象的すぎていろいろな投稿物に使えてしまうのでもう少し具体的な名前の方が良いですね。

ReviewPostにしようと思います！

> レビューを承認したとき、 done を true とする理解であっていますでしょうか？
もしそうであれば、ここは承認した時刻を知りたくなる可能性があるので、Datetimeとしておくと良いかもしれません

合っています🙆‍♂️ こちらDatetimeに修正しました。

> お礼・フィードバックは、1つのレビューに対して1回ずつしかできない、という仕様で合っていますか？
レビューが1回で終わらない場合(修正して欲しい箇所がある場合)にどうするのかが気になりました。

1度レビューしたら終わりではなく、レビューする側がApproveしたタイミングでフィードバック・お礼に移行する想定です！

> お礼・フィードバックは空入力にできないという仕様で合っていますか？
もし空入力を許容すると、レビュー完了・フィードバック完了というステータスを判定する手段がないように見えました。
別途 status のようなカラムを設けるか、お礼日時・フィードバック日時のようなカラムを用意しても良いかもしれません

合っています🙆‍♂️

> これはペーパープロトタイプに対する質問ですが、レビューの申し出があったものの、承認したくない(別の人にレビューして欲しい)場合、拒否する手段はあるのでしょうか？

現状は無いです！ただリリース後にニーズがあれば機能追加していく予定です！

> Languageテーブルの主キーは language という理解で良いでしょうか？Railsで作るなら id を別途設けておいた方が作りやすいと思われるため確認しています。

分かりにくく申し訳ないです🙇‍♂️ Languageの主キーはidです！

> Notificationについてユーザーとのリレーションは不要でしょうか？
もし不要である場合、 checked は誰が確認したことを示すのか気になりました

ユーザーとのリレーションは必要なので、修正しました！

**Comment by yuuu** [comment]
@daiki0381 
確認ありがとうございます 👍 追加でいくつかコメントしますね。

> ReviewPostにしようと思います！

大抵のリソースはPostするものなので `Review` としてはどうでしょうか？

> 1度レビューしたら終わりではなく、レビューする側がApproveしたタイミングでフィードバック・お礼に移行する想定です！

なるほど。ということはレビューの中身のやり取りはGitHubで行うということですね。

> 現状は無いです！ただリリース後にニーズがあれば機能追加していく予定です！

レビューをしてくれる人が現れて、どうしてもその人にレビューしてほしくないと感じたときに、承認をせずそのレビューを放置するしかなくなるのではないでしょうか？拒否ができないのであれば、承認フロー自体が不要な気がします。

その他の点については承知いたしました。問題ないと思います 👍

**Comment by daiki0381** [comment]
@yuuu レビューありがとうございます🙇‍♂️

> 大抵のリソースはPostするものなので Review としてはどうでしょうか？

Reviewにしようと思います！

> なるほど。ということはレビューの中身のやり取りはGitHubで行うということですね。

そうです！

> レビューをしてくれる人が現れて、どうしてもその人にレビューしてほしくないと感じたときに、承認をせずそのレビューを放置するしかなくなるのではないでしょうか？拒否ができないのであれば、承認フロー自体が不要な気がします。

レビューされる側はこの人にレビューしてもらうかを選択することはできないです。このサービスは技術力に関係なく、誰でもレビューしたり、されたりすることができるサービスにしたいので、レビューする側に拒否権を持たせると、それなりに技術力を持つ人でないとレビューすることができなくなってしまったり、レビューしたい！と思うユーザーの方が少ないと思うので、マッチが産まれにくくなってしまうと考えたからです。現在の想定では、レビューする側が承諾ボタンをクリックすると下記の3つの処理が走ります。

①レビュー募集終了になる
②レビューされる側に「〇〇さんがレビューを承諾しました。プルリクエストにコメントが来たら、返信をお願いします。」と通知がされる
③リポジトリのコラボレーターに追加、招待の承認、レビューリクエストがされる

**Comment by yuuu** [comment]
@daiki0381 
なるほど、承諾ボタンはレビューされる側ではなく、する側がクリックするのですね。逆だと勘違いしていました 😅 
であればこれでOKです 👍
